# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 'Angular PR Build'
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    cd AngularApp
    npm install -g @angular/cli@8.0.2
    npm install
    npm run build
    npm run generate-report1
    npm run postbuild
  displayName: 'npm install and build'
